services:
  - type: web
    name: Du-doan-benh-tim
    env: python
    pythonVersion: 3.12
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true